# Generated by Django 4.2 on 2024-08-03 07:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_expensecategory_level_expensecategory_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
