# Generated by Django 4.2 on 2024-08-07 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_expense_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategoriesexpense',
            name='expanse_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensecategory'),
            preserve_default=False,
        ),
    ]
